// data reducer types
export const FETCHING_MORE_POSTS = "FETCHING_MORE_POSTS";
export const SET_POSTS = "SET_POSTS";
export const LOADING_POSTS = "LOADING_POSTS";
export const SET_TOTAL_POSTS_COUNT = "SET_TOTAL_POSTS_COUNT";
export const SET_MORE_POSTS = "SET_MORE_POSTS";
export const SET_POST_COMMENTS = "SET_POST_COMMENTS";
export const SET_POST_COMMENT = "SET_POST_COMMENT";
export const SET_COMMENT_REPLY = "SET_COMMENT_REPLY";
export const SET_COMMENT_REPLY_1 = "SET_COMMENT_REPLY_1";
export const SET_COMMENT_REPLY_2 = "SET_COMMENT_REPLY_2";
export const SET_COMMENT_REPLY_3 = "SET_COMMENT_REPLY_3";
export const SET_COMMENT_REPLY_4 = "SET_COMMENT_REPLY_4";
export const SET_COMMENT_REPLY_5 = "SET_COMMENT_REPLY_5";
