/** UI reducer types **/

export const SET_FEATURED_NAV_CATEGORIES = "SET_FEATURED_NAV_CATEGORIES";
// light and dark mode
export const DARK_MODE_ON = "DARK_MODE_ON";
export const DARK_MODE_OFF = "DARK_MODE_OFF";

// status types
export const SET_STATUS = "SET_STATUS";
export const CLEAR_STATUS = "CLEAR_STATUS";
export const SET_RESET_PASSWORD_STATUS = "SET_RESET_PASSWORD_STATUS";
export const CLEAR_RESET_PASSWORD_STATUS = "CLEAR_RESET_PASSWORD_STATUS";
export const SET_REPLY_STATUS = "SET_REPLY_STATUS";
export const SET_REPLY_STATUS_1 = "SET_REPLY_STATUS_1";
export const SET_REPLY_STATUS_2 = "SET_REPLY_STATUS_2";
export const SET_REPLY_STATUS_3 = "SET_REPLY_STATUS_3";
export const SET_REPLY_STATUS_4 = "SET_REPLY_STATUS_4";
export const SET_REPLY_STATUS_5 = "SET_REPLY_STATUS_5";
export const SELECT_SHRINE = "SELECT_SHRINE";

// error types
export const SET_ERRORS = "SET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_LOGIN_ERRORS = "SET_LOGIN_ERRORS";
export const CLEAR_LOGIN_ERRORS = "CLEAR_LOGIN_ERRORS";
export const SET_SIGNUP_ERRORS = "SET_SIGNUP_ERRORS";
export const CLEAR_SIGNUP_ERRORS = "CLEAR_SIGNUP_ERRORS";
export const SET_RESET_PASSWORD_ERRORS = "SET_RESET_PASSWORD_ERRORS";
export const CLEAR_RESET_PASSWORD_ERRORS = "CLEAR_RESET_PASSWORD_ERRORS";
export const SET_REPLY_FORM_ERRORS = "SET_REPLY_FORM_ERRORS";
export const CLEAR_REPLY_FORM_ERRORS = "CLEAR_REPLY_FORM_ERRORS";
export const SET_COMMENT_REPLY_FORM_ERRORS_1 =
  "SET_COMMENT_REPLY_FORM_ERRORS_1";
export const CLEAR_COMMENT_REPLY_FORM_ERRORS_1 =
  "CLEAR_COMMENT_REPLY_FORM_ERRORS_1";
export const SET_COMMENT_REPLY_FORM_ERRORS_2 =
  "SET_COMMENT_REPLY_FORM_ERRORS_2";
export const CLEAR_COMMENT_REPLY_FORM_ERRORS_2 =
  "CLEAR_COMMENT_REPLY_FORM_ERRORS_2";
export const SET_COMMENT_REPLY_FORM_ERRORS_3 =
  "SET_COMMENT_REPLY_FORM_ERRORS_3";
export const CLEAR_COMMENT_REPLY_FORM_ERRORS_3 =
  "CLEAR_COMMENT_REPLY_FORM_ERRORS_3";
export const SET_COMMENT_REPLY_FORM_ERRORS_4 =
  "SET_COMMENT_REPLY_FORM_ERRORS_4";
export const CLEAR_COMMENT_REPLY_FORM_ERRORS_4 =
  "CLEAR_COMMENT_REPLY_FORM_ERRORS_4";
export const SET_COMMENT_REPLY_FORM_ERRORS_5 =
  "SET_COMMENT_REPLY_FORM_ERRORS_5";
export const CLEAR_COMMENT_REPLY_FORM_ERRORS_5 =
  "CLEAR_COMMENT_REPLY_FORM_ERRORS_5";
export const SET_CREATE_COMMENT_ERRORS = "SET_CREATE_COMMENT_ERRORS";
export const CLEAR_CREATE_COMMENT_ERRORS = "CLEAR_CREATE_COMMENT_ERRORS";

// loading types
export const SET_LOADING_COMPONENT_POSTS = "SET_LOADING_COMPONENT_POSTS";
export const STOP_LOADING_COMPONENT_POSTS = "STOP_LOADING_COMPONENT_POSTS";
export const SET_LOADING_USER_SAVED_POSTS = "SET_LOADING_USER_SAVED_POSTS ";
export const STOP_LOADING_USER_SAVED_POSTS = "STOP_LOADING_USER_SAVED_POSTS ";
export const LOADING_USER = "LOADING_USER";
export const STOP_LOADING_USER = "STOP_LOADING_USER";
