// user reducer types

export const SET_SUBSCRIBED_SHRINES = "SET_SUBSCRIBED_SHRINES";
export const SET_USER = "SET_USER";
export const SET_MORE_AUTH_SHRINES_FOR_INFINITE_SCROLL =
  "SET_MORE_AUTH_SHRINES_FOR_INFINITE_SCROLL";
export const RESET_AUTH_SHRINES_FOR_INFINITE_SCROLL =
  "RESET_AUTH_SHRINES_FOR_INFINITE_SCROLL";
export const ADD_USER_LIKES = "ADD_USER_LIKES";
export const REMOVE_USER_LIKE = "REMOVE_USER_LIKE";
